require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )',
    __dir__
  ]
).strip

platform :ios, '15.1'

prepare_react_native_project!

def patch_fmt_consteval_for_xcode_26(installer)
  fmt_base_header = File.join(
    installer.sandbox.root.to_s,
    'fmt',
    'include',
    'fmt',
    'base.h'
  )
  return unless File.exist?(fmt_base_header)

  contents = File.read(fmt_base_header)
  original_check = '#elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L'
  patched_check = '#elif defined(__apple_build_version__) && (__apple_build_version__ < 14000029L || __apple_build_version__ >= 21000000L)'
  return if contents.include?(patched_check)
  return unless contents.include?(original_check)

  File.chmod(0644, fmt_base_header)
  File.write(fmt_base_header, contents.sub(original_check, patched_check))
end

target 'HealthApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    patch_fmt_consteval_for_xcode_26(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|

        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

        # React Native 0.82 requires C++20
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'

        # Don't fail on warnings
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'

        # Disable Xcode 26 strict errors for RN pod source files
        config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=deprecated-objc-isa-usage'
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=return-type'
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=unreachable-code'
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=unused-variable'
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=unused-function'
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=objc-root-class'
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=non-modular-include-in-framework-module'

        config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=deprecated-objc-isa-usage'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=return-type'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=unreachable-code'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=unused-variable'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=unused-function'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=objc-root-class'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=non-modular-include-in-framework-module'

        # Enable modules
        config.build_settings['CLANG_CXX_ENABLE_MODULES'] = 'YES'

        # Allow non-modular includes inside framework modules for pods that require it
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

        # ARC
        config.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'

      end
    end
  end
end
